-- Users schema

-- !Ups
CREATE TABLE users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255),
  email VARCHAR(255),
  email_verified BOOLEAN DEFAULT FALSE,
  google_id VARCHAR(255),
  google_access_token VARCHAR(2048),
  google_refresh_token VARCHAR(2048),
  google_token_expires_at BIGINT,
  picture_url VARCHAR(500),
  oauth_linked_at TIMESTAMP
);

CREATE INDEX idx_users_google_id ON users(google_id);
CREATE INDEX idx_users_email ON users(email);

-- !Downs
DROP TABLE IF EXISTS users;