# .scalafmt.conf
version = "3.7.17"
runner.dialect = scala213
maxColumn = 120
indent.main = 2
indent.defnSite = 2
align.preset = more
assumeStandardLibraryStripMargin = true
docstrings.style = Asterisk
docstrings.wrap = no
lineEndings = unix
rewrite.rules = [RedundantBraces, RedundantParens]
