# https://www.playframework.com/documentation/latest/Configuration

# Slick Configuration
slick.dbs.default.profile = "slick.jdbc.H2Profile$"
slick.dbs.default.db.driver = "org.h2.Driver"
slick.dbs.default.db.url = "jdbc:h2:mem:play;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE"
slick.dbs.default.db.user = "sa"
slick.dbs.default.db.password = ""

# Optional: Enable Evolutions (Automated Table Creation)
play.evolutions.enabled = true
play.evolutions.autoApply = true

# play.modules.enabled += "modules.ActorModule"

# JWT Configuration
jwt {
    secret = "your-super-secret-key-change-this-in-production-min-32-chars"
    expiry-minutes = 60
}